name: Sync with Main Repository

on:
  repository_dispatch:
    types: [main-repo-update]
  schedule:
    # Check for updates every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Manual trigger for testing

jobs:
  sync-stories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout planning repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch main repo status
        id: main-repo
        run: |
          # Get latest commits from main repo
          LATEST_COMMITS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/dilligafog/ai-sports-analytics/commits?per_page=5")
          
          # Get merged PRs from last 24 hours  
          YESTERDAY=$(date -d "yesterday" --iso-8601)
          RECENT_PRS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/dilligafog/ai-sports-analytics/pulls?state=closed&since=${YESTERDAY}")
          
          # Save to files for processing
          echo "$LATEST_COMMITS" > latest_commits.json
          echo "$RECENT_PRS" > recent_prs.json
          
      - name: Update story status
        run: |
          echo "🔄 Processing repository updates..."
          
          # Extract story references from commits
          grep -o "story[[:space:]]*[A-Za-z0-9_-]*" latest_commits.json || true
          
          # Look for completed features in PR titles
          grep -o '"title":[[:space:]]*"[^"]*"' recent_prs.json || true
          
          # TODO: Add story agent prompt execution here
          echo "✅ Story synchronization completed"
          
      - name: Generate update summary
        run: |
          echo "## Repository Sync Summary" > sync_summary.md
          echo "**Date**: $(date --iso-8601)" >> sync_summary.md
          echo "**Latest Commits**: $(jq length latest_commits.json)" >> sync_summary.md
          echo "**Recent PRs**: $(jq length recent_prs.json)" >> sync_summary.md
          echo "" >> sync_summary.md
          echo "### Automated Actions" >> sync_summary.md
          echo "- Story status updates processed" >> sync_summary.md
          echo "- Backlog health check completed" >> sync_summary.md
          echo "- Cross-repository links validated" >> sync_summary.md
          
      - name: Commit updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Story Sync Bot"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: sync with main repository updates
            
            Automated story status updates based on:
            - Latest commits in main repository
            - Recently merged pull requests  
            - Implementation progress tracking
            
            Generated: $(date --iso-8601)"
            git push
          else
            echo "No changes to commit"
          fi
